### ISSUE TITLE
maybe we can use  SingleFile

### ISSUE THREAD

**Issue by yihong0618** [ghostincoolshell/haoel-articles#1]
https://github.com/gildas-lormeau/SingleFile

**Comment by hongqn** [comment]
可以的，如果能够配合一个 html -> markdown 工具，产出的结果可能更易用

**Comment by kaiix** [comment]
Full-text RSS is another way for backing up the blog articles

**Comment by hongqn** [comment]
先把已有的数据放到 repo 里吧。我抽空的时候[写个 README](#3) ，阐述一下这个项目的目的和做法，也方便后续开展

**Comment by hongqn** [comment]
https://coolshell.cn/about ：

> 除非文章内特别说明，你可以转载酷壳的文章，但请加入文章作者和出处。谢谢。

酷壳的文章是可以转载的，有 RSS 抓取工具的话，可以直接提交进来吧。

**Comment by yzqzss** [comment]
通过 RSS 做存档不适合，coolshell 文章时间跨度太长（2004～），而博客 RSS 只输出最新10篇。我在 2020 年开始订阅，到现在也只[积累到 30 几篇](https://box.othing.xyz/i/?get=f_25)。feedly/inoreader 的缓存不用考虑，十多年前的文章，缓存的图片是否坏链都说不一定。

还好 coolshell 就是一个简单的 WordPress 站，站点结构也不特殊，随便找些存档工具就能存。不太推荐用 SingleFile ，存的时候爽，到时候要做后期处理就麻烦了。它只适合存单页，不适合整站存档。

现在最大的问题就是 coolshell 访问量太多，全靠 CloudFlare 的缓存撑着。随便向回源 IP 发一个首页请求：`Dynamic page generated in 19.107 seconds.`，花了近20秒才渲染出来……（更大概率是直接 502 ……）

等凌晨访问的人少了再做存档吧。我已经在 [ArchiveTeam](https://wiki.archiveteam.org/) IRC 里留言了，等 coolshell 服务器稳定之后，他们会用 ArchiveBot 做存档然后上传到 Wayback Machine。这种规规矩矩的 WordPress 站很好处理的。

---

然后如果要把 coolshell 文章转成 markdown ，然后做一个“纪念站”的话。html 转 markdown 好解决，库很多。就是图片之类的外链需要下载下来本地化，不知道有没有什么方便的工具/库。

**Comment by hongqn** [comment]
感谢。这样最坏情况下可以从 Wayback Machine 抓取数据进行备份。

至于图片，在有 html 的情况下可以通过 HTML parser （比如 Python 的 lxml.html）遍历 a 标签取 href 拼 URL 吧。只要源站没有做反爬，应该还是可以用较小代价获取的。

如果老文章图片已经坏链确实会比较麻烦。

**Comment by kaiix** [comment]
> 通过 RSS 做存档不适合，coolshell 文章时间跨度太长（2004～），而博客 RSS 只输出最新10篇。我在 2020 年开始订阅，到现在也只[积累到 30 几篇](https://box.othing.xyz/i/?get=f_25)。feedly/inoreader 的缓存不用考虑，十多年前的文章，缓存的图片是否坏链都说不一定。
> 
> 还好 coolshell 就是一个简单的 WordPress 站，站点结构也不特殊，随便找些存档工具就能存。不太推荐用 SingleFile ，存的时候爽，到时候要做后期处理就麻烦了。它只适合存单页，不适合整站存档。
> 
> 现在最大的问题就是 coolshell 访问量太多，全靠 CloudFlare 的缓存撑着。随便向回源 IP 发一个首页请求：`Dynamic page generated in 19.107 seconds.`，花了近20秒才渲染出来……（更大概率是直接 502 ……）
> 
> 等凌晨访问的人少了再做存档吧。我已经在 [ArchiveTeam](https://wiki.archiveteam.org/) IRC 里留言了，等 coolshell 服务器稳定之后，他们会用 ArchiveBot 做存档然后上传到 Wayback Machine。这种规规矩矩的 WordPress 站很好处理的。
> 
> 然后如果要把 coolshell 文章转成 markdown ，然后做一个“纪念站”的话。html 转 markdown 好解决，库很多。就是图片之类的外链需要下载下来本地化，不知道有没有什么方便的工具/库。

https://coolshell.cn 是基于 wordpress 的, feed 支持分页, 例如 https://coolshell.cn/feed?paged=25 ([feed-page25.txt](https://github.com/ghostincoolshell/haoel-articles/files/11477383/feed-page25.txt)) 所以应该是可以获得全部文章的. 不过目前源站不稳定, 无法正常抓取.

**Comment by yzqzss** [comment]
> https://coolshell.cn 是基于 wordpress 的, feed 支持分页, 例如 https://coolshell.cn/feed?paged=25 ([feed-page25.txt](https://github.com/ghostincoolshell/haoel-articles/files/11477383/feed-page25.txt)) 所以应该是可以获得全部文章的. 不过目前源站不稳定, 无法正常抓取.

感谢！竟然可以翻页，我火星了。我马上开工！

**Comment by yzqzss** [comment]
![p1](https://github.com/ghostincoolshell/haoel-articles/assets/30341059/2f15b3d8-1182-40a2-885e-28bd7c42c79e)

我开工了……但就像你说的，根本无法正常抓取。回源也 502 。

update: 现在状况好了一点， wordpress 能赶在 nginx 超时之前响应rss了。我在存。

完成了： #6

**Comment by hongqn** [comment]
感谢 @yzqzss ！ #6 已经合并。
