### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by xlmo** [ghostincoolshell/haoel-articles#13]
git clone https://github.com/ghostincoolshell/haoel-articles
Cloning into 'haoel-articles'...
remote: Enumerating objects: 4882, done.
remote: Counting objects: 100% (761/761), done.
remote: Compressing objects: 100% (750/750), done.
remote: Total 4882 (delta 52), reused 36 (delta 11), pack-reused 4121
Receiving objects: 100% (4882/4882), 88.76 MiB | 6.16 MiB/s, done.
Resolving deltas: 100% (1075/1075), done.
**error: invalid path 'blogs/rss2html/2004-6-23: C++ STL string的Copy-On-Write技术.html'
fatal: unable to checkout working tree**
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by kaiix** [comment]
maybe this can help https://stackoverflow.com/a/61623028

`git config --system core.longpaths true`

**Comment by hongqn** [comment]
会不会是由于文件名中有冒号，可能有 Windows 文件系统的兼容性问题？

**Comment by xlmo** [comment]
是的。在Linux下正常。Windows下报错。

**Comment by hongqn** [comment]
@xlmo 已经修正了文件名，请再次尝试在 Windows 下 clone 吧，谢谢。如果还有问题请 reopen 这个 issue 。

**Comment by xlmo** [comment]
@hongqn 
这个也有问题。
error: invalid path 'blogs/rss2html/2009-11-30 Javascript程序员嘴最脏??.html'

**Comment by hongqn** [comment]
`?` 也是不合法的 windows 文件名字符。但是目前 `blogs/wp-content` 下存在一些名字中含有 `?` 的图像文件，比如 [`blogs/wp-content/uploads/2012/05/aggregates-joins.png?w=594`](https://github.com/ghostincoolshell/haoel-articles/blob/31c0b9bdb37b8f259a13e9b21beb6df347372028/blogs/wp-content/uploads/2012/05/aggregates-joins.png%3Fw%3D594) ，可能也要改下名字，以及修改引用 URL 

@kaiix 有空看看？

**Comment by hongqn** [comment]
按照 https://stackoverflow.com/a/31976060 检查了一下，除了 `?` ，目前的文件中还有 `*` 和 `>` 也是不合法的 windows 文件名字符。

会都改掉

**Comment by hongqn** [comment]
@xlmo 这次应该可以了（吧

**Comment by xlmo** [comment]
可以了，辛苦了，非常感谢！
