### ISSUE TITLE
Serve the blog in github pages

### ISSUE THREAD

**Issue by kaiix** [ghostincoolshell/haoel-articles#14]
Use [mkdocs](https://squidfunk.github.io/mkdocs-material/) to generate a static site and serve it on github pages

quick preview:

<img width="1533" alt="image" src="https://github.com/ghostincoolshell/haoel-articles/assets/172202/1db49bc7-64a1-4276-9d08-cd96e376f983">

**Comment by hongqn** [comment]
我把 ghostincoolshell.com 重定向到 https://ghostincoolshell.github.io/haoel-articles/ 了
