### ISSUE TITLE
gh-pages branch as a mirror of coolshell.cn ?

### ISSUE THREAD

**Issue by chenshuo** [ghostincoolshell/haoel-articles#23]
e.g. Merge/copy the `main` branch of https://github.com/chenshuo/coolshell as `gh-pages` of this repo ?

**Comment by kaiix** [comment]
Great job, it's almost a full site clone.

**Comment by kaiix** [comment]
For anyone who wants to mirror the site, you can use the following command

```shell
wget --mirror --convert-links --adjust-extension --page-requisites --no-parent http://example.org
```

ref: https://www.guyrutenberg.com/2014/05/02/make-offline-mirror-of-a-site-using-wget/

**Comment by hongqn** [comment]
https://coolshell.org is awesome! Let's put a link to it in this repo's pages to help more people access it.

**Comment by hongqn** [comment]
在 https://ghostincoolshell.github.io/haoel-articles/ 已增加链接。

P.S. 发现 mkdocs 不会自动将 URL 转换成 `<a>` 链接，得在 markdown 里显式写成链接。
