### ISSUE TITLE
微博数据抓取方法

### ISSUE THREAD

**Issue by hongqn** [ghostincoolshell/haoel-articles#5]
耗子在微博上也有不少输出。微博有类似 twint 这种工具吗

**Comment by yzqzss** [comment]
https://github.com/meterscao/Speechless

**Comment by hongqn** [comment]
我用 Speechless 只能抓到最近几个月的微博 😢 输出是 PDF 格式的。

再研究看看还有没有其它的工具。

**Comment by hongqn** [comment]
明白了，是耗子设置了仅半年可见，那应该就只能抓到这么多了。我先把 PDF 传进来吧，未来看看是否能解析。

**Comment by hongqn** [comment]
等对亲属最难熬的这段时间过去了，找渠道问一下耗子家属对数据处理的意见吧。如果家属同意，并且愿意开放更早的微博数据，我们再跟进。如果家属不同意，就让那些数据继续沉默吧。
