### ISSUE TITLE
抢救博客文章里的图片

### ISSUE THREAD

**Issue by yzqzss** [ghostincoolshell/haoel-articles#8]
很多早期文章的图片都坏链了。

接下来需要：

1. 下载所有还能正常访问的图片。 （#11 完成了站内图）
2. 如果坏链的图片可以从 Wayback Machine 里找到。一样，下载。
   > 可以在图片 URL 前面加上 `http://web.archive.org/web/1if_/` 来判断。（用 SPN2 API 查不一定准）  
3. 检查还能正常访问的图片是否都在 Wayback Machine 里有快照。如果没有，用 SPN2 API 提交快照。
4. 将 Markdown 里的图片链接指向本地。（ #11 完成了站内图）

---

不过，我得先睡觉了。
:)

**Comment by hongqn** [comment]
fixed in #11
